name: backend

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  Build:
    name: Build the App
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: psycopg2 prerequisites
        run: sudo apt-get install libpq-dev
      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run migrations
        working-directory: ./backend
        run: python manage.py migrate
      - name: Run Tests
        working-directory: ./backend
        run: |
          python manage.py test
  Coverege:
    name: codecov
    runs-on: ubuntu-latest
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
    
