name: backend

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  Build:
    name: Build the App
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run migrations
        run: python manage.py migrate
      
      - name: Build the App
        working-directory: ./backend
        run: |
          python manage.py runserver
      - name: Run Tests
        run: |
          python manage.py test
  Coverege:
    name: codecov
    runs-on: ubuntu-latest
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
    
