name: Frontend-Pipeline

on:
  push:
    branches:
      - main
      - OODP-60-frontend-ci-cd

jobs:
  UnitTest:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        working-directory: ./frontend
        run: |
          echo "Installing Dependencies ..."
          npm install
      - name: Run Tests
        working-directory: ./frontend
        run: |
          echo "Running Tests ..."
          npm test
        env:
          CI: true